default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: appception_development

test:
  <<: *default
  database: appception_test

production:
  <<: *default
  database: appception_production
